---
engines:
 rubocop:
   enabled: true

pylint:
  enabled: true
  python_version: 3

exclude_paths:
  - '.github/**'
  - '**.md'
  - 'docs/**'
  - scorer/__init__.py
  - scorer/Scorer/__init__.py
  - docker/**
  - build.ps1
  - build.sh
  - setup.py
