image: Visual Studio 2017
clone_folder: c:\projects\Scorer
configuration: Debug

environment:
    matrix:
    - platform: Win32
      COMPILER: vs
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      MSVC_SETUP_ARG: x86
    - platform: Win64
      COMPILER: vs
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      MSVC_SETUP_ARG: x64

install:
  - if [%COMPILER%]==[vs] cinst cmake ninja
  - if [%COMPILER%]==[vs] SET "PATH=C:\Program Files\CMake\bin;%PATH%"
  - if [%COMPILER%]==[vs] SET "PATH=C:\Program Files\LLVM\bin;%PATH%"
  - if [%COMPILER%]==[vs] call "%MSVC_SETUP_PATH%" %MSVC_SETUP_ARG%
  - git submodule -q update --init --recursive

before_build:
  - cd C:\projects\Scorer
  - mkdir build
  - cd build

build_script:
  - if [%COMPILER%]==[vs] cmake -G "Ninja" ..
  - if [%COMPILER%]==[vs] cmake --build .
